### PR TITLE
release/1.13.00

### LINKED ISSUE #46: WEBSITE STOCK ISSUES
@patpluspun - please look at this as a priority issue. Thanks - J

From: Renata Watt
Sent: Monday, 20 April 2015 3:15 PM
To: Emily Wan
Cc: Doug Wasley
Subject: WEBSITE STOCK ISSUES

Hi Emily,

An online customer has been able order an item from the website that is showing a negative stock balance on the AS400. They have ordered and paid for an item that is showing -11 in stock. Obviously there is some issue there as I was under the impression when the website was set up that stock showing under 50 or 100 (can’t remember which) would automatically be made unavailable – hence the weekly updates you do with the stock file.

Not sure if this is something that needs to be raised with the website people to check.

I have had other titles over the last few months also come through ( can’t recall which ones but they have all been titles that have been out of stock for a long time).

 

The title in this recent order is ISBN 9781743002605 EXERCISES FOR LETTING GO.

 

It may be just a setting why these titles are slipping through but I know I have checked with Doug before and each time the stock files represent what the AS400 shows that there is no stock but customers are still able to purchase the item??

### LINKED ISSUE #60: BED - Error on 'Garden Friends Buggy Book'
http://www.fivemile.com.au/catalog/board-books/garden-friends-buggy-book

Please investigate the error that is happening on this page.

web error

### PR DESCRIPTION
**Pull request by patpluspun**
Fixes #60 
Fixes #46

### CODE REVIEW

**Comment by janetgatsby** [comment]
@patpluspun what about #46 add a checkbox for "Published, preorder"??

**Comment by patpluspun** [comment]
I'm working on that right now.

**Comment by patpluspun** [comment]
@janetgatsby this release is now ready on http://test.fivemile.com.au

Please review, and sign off when ready and I will make this happen.

**Comment by janetgatsby** [comment]
checkin now

**Comment by janetgatsby** [comment]
@patpluspun both tested on test and looking good, let's go!

**Pull request merged**
