### PR TITLE
hotfix/1.11.01

### PR DESCRIPTION
**Pull request by patpluspun**

### CODE REVIEW

**Comment by janetgatsby** [comment]
what's included?

**Comment by patpluspun** [comment]
This should cover both #28 and #31, as well as security updates for modules and drupal core.  I am not 100% sure on #28 as it kind of relates to #27 but as long as the admins are getting email, it should work.  Basically it's using the customer template, which includes all the shipping info, instead of the admin template.

**Comment by janetgatsby** [comment]
Awesome, thanks. I'll ask Emily to verify what customer service gets for #28

**Comment by janetgatsby** [comment]
make it so

**Comment by patpluspun** [comment]
All changes are ready to push.  There is a small database update, so I'll take the site down for a brief moment.  Just say when to start.

**Comment by patpluspun** [comment]
@janetgatsby production has been updated and caches cleared.  I see no problems so far, but I must head home now.  I'll resume checking once I'm back.

**Comment by janetgatsby** [comment]
@patpluspun I figured you would stay up later than me :) Did you get an opportunity to look at any other issues?

**Pull request merged**
