### PR TITLE
Release/1.12.00

### LINKED ISSUE #40: Untagging a ‘New Release’ causes ‘infinite loop’ for URL redirects
@patpluspun please investigate this latest issue and let give me a diagnosis or fix.

Hi Janet

I’m having ongoing issues with the bug mentioned below. It seems to be that every time a book is untagged as a ‘New Release’ it creates an ‘infinite loop’ for which URL redirects need to be deleted.

At first I only thought this applied to books for which bit.ly URL redirects were assigned to it, but now it seems once a book untagged from being a ‘New Release’ the system is self-creating URL redirects.

Once a book has had the ‘New Releases’ tag removed and I save it, I get the message ‘Oops, looks likethis request tried to create an infinite loop…’ (see screen shot infinite loop). The only way I can remove this message is by following Patrick’s advice below and deleting all URL redirects (see screen shot URL redirects).

It’s strange, as I didn’t create URL redirects for most of the books for which this has occurred today, and both need to be deleted before the message disappeared.

Could this please be investigated and a permanent fix found?    

Thank you

Emily

### LINKED ISSUE #45: 'Related Products' not working
Hi Janet

 

I have noticed that ‘Related Products’ is not working.

 

When I’m adding a title to the website and I add a book to the ‘Related Products’ section, it is not showing on the live website.

 

Please see example attached and below, The Rig appears in the ‘Related Products’ section in the Content Management System, but is not appearing on the live website (see link).

 

The only way I could get it to appear on the live site is to add it to the ‘We Also Recommend’ section. It should only be in ‘Related Products’.  

http://www.fivemile.com.au/catalog/new-releases/crystal-force

 

Could you please add this to the list of issues to be fixed?

 

Many thanks
related products

### PR DESCRIPTION
**Pull request by patpluspun**
Drupal module updates and a few fixes:

Closes #40 
Closes #45

### CODE REVIEW

**Comment by patpluspun** [comment]
@janetgatsby sorry for the delay, I had some real issues getting JS fixed on test.  For some reason it breaks horribly if aggregation is turned on.  I'll investigate it over this week, along with new tickets.  This release is ready to review on test though.

**Comment by janetgatsby** [comment]
@patpluspun I'm Janet Stearns and I approve this message!

**Comment by patpluspun** [comment]
so, ready to go to production?  If not, let me know, I'll be here all night.  Thank you, and remember to tip your servers.

**Comment by janetgatsby** [comment]
Try the veal.

Yes please go to production.

**Comment by patpluspun** [comment]
Maintenance mode now.  Will edit this message when done.

**Pull request merged**
