### PR TITLE
release/1.17.00

### PR DESCRIPTION
**Pull request by patpluspun**

### CODE REVIEW

**Comment by patpluspun** [comment]
@janetgatsby I have pushed the changes so far to test.  Please review it when you get a chance.  The only way I could get it working was to create a new shipping quote with the correct conditions.  The drawback is that Australia has to have two shipping methods visible, standard and free shipping after $50.

I can possibly default to the free shipping if it qualifies and hide the other option, but this will take more time, so let's find out from Emily if it's necessary or not (or feel free to make the judgment yourself).

The price can be changed from here: http://test.fivemile.com.au/admin/store/settings/quotes  Just click conditions on the Free Shipping with $50 Purchase quote, then edit the Data Comparison.  50.00 at the bottom is the current value, but it can be switched to any floating point number.

**Comment by janetgatsby** [comment]
@patpluspun 
My thought is that it's fine the way it is. I don't see the free shipping option until I have more than $50 in my cart and I can't imagine why anyone would change the default selected from "free" to "yes please charge me".

Let's get this on dev today. Emily can test it there and we can switch before her October need-by timeframe.

**Comment by patpluspun** [comment]
This is already on dev, I'll go ahead and include it in today's release!

**Comment by janetgatsby** [comment]
@patpluspun I need to get to bed, have an early morning tomorrow. Please deploy what you can to live tonight and I'll check everything in the am.  Thanks Patrick!

**Comment by patpluspun** [comment]
I'm just fixing the featured block on ebooks page, and I'll deploy.

**Pull request merged**
