### PR TITLE
hotfix/1.12.01

### PR DESCRIPTION
**Pull request by patpluspun**
Addresses #45
Addresses #56 
Updates Drupal core
Updates jquery_update module

### CODE REVIEW

**Comment by janetgatsby** [comment]
go for deploy!

**Comment by janetgatsby** [comment]
Confirmed functionality on DEV

**Comment by patpluspun** [comment]
It is pulled and updated on production.  Please verify, and then it's time for a celebratory screwdriver!

**Comment by janetgatsby** [comment]
Verified on production, thank you very much.

**Pull request merged**
